[package]
name = "osu-verification"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
handlebars.workspace = true
moth_core = { path = "../moth_core" }
rosu-v2.workspace = true
serde.workspace = true
tokio.workspace = true
tower-http = { version = "0.6", features = ["cors"] }
